spring.data.mongodb.uri=mongodb+srv://studyhive47:T4KRFNwClyD8hHRz@cluster0.t2sct.mongodb.net/studyhive?retryWrites=true&w=majority&appName=Cluster0

spring.servlet.multipart.enabled = true
spring.servlet.multipart.max-file-size = 200MB
spring.servlet.multipart.max-request-size = 200MB

